---
- name: Install the latest version of PHP Packages
  yum:
    name: "{{ php_packages }}"
    state: latest
    enablerepo: "epel,{{ remi_repository_name }}"

- name: Install Composer
  get_url:
    url: "{{ composer_phar_url }}"
    dest: /usr/local/bin/composer
    mode: 0555

- name: Install the latest version of unzip for composer
  yum: name=unzip state=latest

- name: Install the latest version of PHP-FPM
  yum:
    name: php-fpm
    state: latest
    enablerepo: "epel,{{ remi_repository_name }}"
  notify: Restart phpfpm

- name: Set user php-fpm.d/www.conf
  lineinfile:
    dest: "{{ phpfpm_conf_dest }}"
    regexp: '^user\s*='
    insertafter: '^\[www\]'
    line: "user={{ phpfpm_user }}"
  notify: Restart phpfpm

- name: Set group php-fpm.d/www.conf
  lineinfile:
    dest: "{{ phpfpm_conf_dest }}"
    regexp: '^group\s*='
    insertafter: '^\[www\]'
    line: "group={{ phpfpm_group }}"
  notify: Restart phpfpm
