---
- name: Install Remi repository
  yum: name={{ remi_repository }}
- name: Install the latest version of yum-utils
  yum: name=yum-utils state=latest
- name: Check PHP version
  shell: yum info php | grep -e "Version\s*:\s*7\."
  register: php_version
  check_mode: no
  changed_when: false
  failed_when: false
- name: Enable Remi repository
  shell: yum-config-manager --enable "{{ remi_repository_name }}"
  when: php_version.stdout == ""

- name: Install the latest version of PHP Packages
  yum: name={{ item }} state=latest
  with_items: "{{ php_packages }}"

- name: Install Composer
  get_url:
    url: "{{ composer_phar_url }}"
    dest: /usr/local/bin/composer
    mode: 0555
- name: Install the latest version of phpDocumentor
  get_url:
    url: "{{ phpdoc_phar_url }}"
    dest: /usr/local/bin/phpdoc
    mode: 0555
- name: Install the latest version of PHPUnit
  get_url:
    url: "{{ phpunit_phar_url }}"
    dest: /usr/local/bin/phpunit
    mode: 0555

- name: Install the latest version of unzip for composer
  yum: name=unzip state=latest
