app_nginx_conf_src: "nginx.conf.j2"
app_nginx_conf_dest: "/etc/nginx/default.d/vagrant.conf"
app_svr_dir: "/vagrant/server"
app_svr_dist_dir: "{{ app_svr_dir }}/public"
app_log_dir: "/var/log/local/game-svr"
app_db:
  - game_master_db
  - game_global_db
app_db_users:
  - user: game_usr
    password: game001
    privilege: "game_master_db.*:ALL/game_global_db.*:ALL" # FIXME: この書き方だと二度目以降のansibleで変更があるとエラーになる模様
